{
    "active": False,
    "auto_install": True,
    "application": False,
    "author": "Marc Wimmer",
    "category": "Tools",
    "css": [],
    "data": [
        "access_rights_tree.xml",
        "ir_act_report.xml",
        "ir_model_access_true.xml",
        "ir_rule_form.xml",
        "ir_rule_tree.xml",
        "ir_ui_act_window.xml",
        "ir_ui_menu_form.xml",
        "ir_ui_menu_tree.xml",
        "ir_ui_view_search.xml",
        "res_groups.xml",
    ],
    "demo_xml": [],
    "depends": ["base", "module_tools", "web"],
    "description": "Displays the xml-ids of a menuitem in the tree",
    "installable": True,
    "js": [],
    "name": "menu_show_xmlid",
    "test": [],
    "version": "17.0.0.0",
    "web": True,
    "assets": {"web.assets_qweb": []},
    "demo": [],
}
